name: seethroughplayers
version: '1.0'
main: com.seethroughplayers.Seethroughplayers
api-version: '1.21'
authors: [ Banker ]
commands:
  seethrough:
    description: Toggle see through players
    usage: /<command>
    permission: seethroughplayers.toggle
